# Generated by Django 3.2 on 2025-03-16 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_rename_last_name_supplier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
    ]
